config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'gear'      => 'gears#index'
  get 'guitars'   => 'posts#index'
  get 'larrivee'  => 'larrivees#index'
  get 'martin'    => 'martins#index'
  get 'blueridge' => 'blueridges#index'
  get 'about'     => 'static_pages#about'

end

app/models/bi_daily_scheduler.rb
class BiDailyScheduler < HerokuScheduler
  def should_run?
    (Time.now.hour % 12) == hour
  end
end

app/models/blueridge.rb
class Blueridge < ActiveRecord::Base
  extend PostUtils
  default_scope { order(:id) }
end

app/models/gear.rb
class Gear < ActiveRecord::Base
  extend PostUtils
  default_scope { order(:id) }
end

app/models/heroku_scheduler.rb
class HerokuScheduler
  attr_reader :hour

  def initialize(args={})
    @hour = args.fetch(:hour,2) % 12
  end

  def schedule
    yield if should_run?
  end

  def should_run?
    true
  end
end

app/models/larrivee.rb
class Larrivee < ActiveRecord::Base
  extend PostUtils
  default_scope { order(:id) }
  before_save  { self.link = link.gsub(/PHPSESSID=.*&/, '') }
end

app/models/martin.rb
class Martin < ActiveRecord::Base
  extend PostUtils
  default_scope { order(:id) }
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend PostUtils
  default_scope { order(:id) }
 
end

app/models/post_utils.rb
module PostUtils
   def create(posts)
    posts.each do |p|
      create!(title: p.title, link: p.link, author: p.author,
              last_post: p.last_post, replies: p.replies, views: p.views)
    end
  end

  def clear_db
    destroy_all
    reset_pk_sequence # reset primary key to 0
  end
end

app/models/quarter_day_scheduler.rb
class QuarterDayScheduler < HerokuScheduler
  def should_run?
    (Time.now.hour - hour) % 6 == 0
  end
end

app/controllers/blueridges_controller.rb
class BlueridgesController < ApplicationController
  def index
    blueridges = Blueridge.all
    @blueridges_presenter = BlueridgePresenter.wrap(blueridges, view_context)
  end
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  def index
    gear = Gear.all
    @gears_presenter = GearPresenter.wrap(gear, view_context)
  end
end

app/controllers/larrivees_controller.rb
class LarriveesController < ApplicationController
  def index
    larrivees = Larrivee.all
    @larrivees_presenter = LarriveePresenter.wrap(larrivees, view_context)
  end
end

app/controllers/martins_controller.rb
class MartinsController < ApplicationController
  def index
    martins = Martin.all
    @martins_presenter = MartinPresenter.wrap(martins, view_context)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    posts = Post.all
    @posts_presenter = PostPresenter.wrap(posts, view_context)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Last_post formats
  FORMATS = [
   /(?<user>.+)\s+(?<date>\d+\/\d+\/\d+.*$)/,
   /(?<user>.+)\s+(?<date>[a-zA-Z]{3} \d+ \d+.*$)/
  ]

  # Splits user and date from parsed column (last_post)
  #
  # ==== Examples
  #
  # "Professor Chaos 12/31/2014 5:57 PM"    # => ["Professor Chaos", "12,31/2014 5:57 PM"]
  # "Johnny Cash II Dec 31 2014 11:59 PM"   # => ["Johnny Cash II", "Dec 31 2014 11:59 PM"]
  # "-"                                     # => ["", ""]
  def format_last_post(post)
    FORMATS.each do |format|
       m = post.match(format)
       return [ m[:user], m[:date] ] if m
    end
    ["",""] # return empty string if no matches found
  end
end

app/helpers/blueridges_helper.rb
module BlueridgesHelper
  def cache_key_for_blueridge
    last_updated_at = Blueridge.last.updated_at.to_i
    "/all-#{last_updated_at}"
  end
end

app/helpers/gear_helper.rb
module GearHelper
  def cache_key_for_gear
    last_updated_at = Gear.last.updated_at.to_i
    "/all-#{last_updated_at}"
  end
end

app/helpers/larrivee_helper.rb
module LarriveeHelper
  def cache_key_for_larrivee
    last_updated_at = Larrivee.last.updated_at.to_i
    "/all-#{last_updated_at}"
  end
end

app/helpers/martin_helper.rb
module MartinHelper
  def cache_key_for_martin
    last_updated_at = Martin.last.updated_at.to_i
    "/all-#{last_updated_at}"
  end

 # def format_martin_last_post(post)
 #   # split text on space between user and date
 #   post.split /\s+(?=\d{1,2}\/\d{1,2}\/\d{2,4})/
 # end

end

app/helpers/posts_helper.rb
module PostsHelper
  def cache_key_for_posts
    last_updated_at = Post.last.updated_at.to_i
    "/all-#{last_updated_at}"
  end
end

app/views/layouts/_footer.html.erb
<footer class="sticky-footer">
  <section class="footer-text">
  <p>
    This website is maintained by <a>@Jberczel</a>. If you have questions
    or suggestions, please see the <%= link_to "About", about_path %> page.
  </p>
  </section>
</footer>

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41079755-3', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/_header.html.erb
<header>
<div class="wrapper2">
  <h2>Search the last 6 months of guitar sales.  Updated hourly.</h2>

  <div class="buttons">
    <%= link_to "Guitars", guitars_path, class: "button" %>
    <%= link_to "Gear",    gear_path,    class: "button" %>
  </div>
</div>
</header>

app/views/layouts/_navbar.html.erb
<nav class="bourbon">
<a href="/">
  <div id="logo">
    <h2 class="logo-acoustic">acoustic</h2>
    <h2 class="logo-guitar">guitar</h2>
    <h2 class="logo-forum">forum {search}</h2>
  </div>
</a>

<div class="nav-link more">
  <a href="javascript:void(0)">Other Forums</a>

  <ul class="submenu">
    <li><%= link_to "Larrivee Forum",  larrivee_path %></li>
    <li><%= link_to "Martin Forum",    martin_path %></li>
    <li><%= link_to "Blueridge Forum", blueridge_path %></li>
  </ul>
</div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AGF ForSale</title>
  <%= stylesheet_link_tag    :application, media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :application, "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class = "<%= controller_name %> <%= action_name %>">

<%= render 'layouts/navbar' %>
<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>
<%= render 'layouts/ga' %>

</body>
</html>

app/views/layouts/ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41079755-3', 'auto');
  ga('send', 'pageview');

</script>

app/views/shared/_auction_links.html.haml
.auction-links
  = link_to "EBAY", "http://www.ebay.com/",   :class => 'ebay-link button',   :target => "_blank"
  = link_to "REVERB", "https://reverb.com/",  :class => 'reverb-link button', :target => "_blank"